/* eslint-disable */
// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "greet", input: string, result: string } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "decrement", input: never, result: null } | 
        { key: "increment", input: never, result: null },
    subscriptions: 
        { key: "count", input: never, result: number }
};
